
services:
  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 commerce.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-g^w5$oj^unmw^p*(&jpb5klc1a7zn-#baxyj(a0+dqd=0+gy2*
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=yourdb
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=e_market
      - POSTGRES_USER=olaneat
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: