services:
  - type: web
    name: commerce
    env: python
    buildCommand: "cd /opt/render/project/src && ./build.sh"
    startCommand: "cd /opt/render/project/src && gunicorn commerce.wsgi:application --bind 0.0.0.0:$PORT --timeout 300 --workers 1"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: commerce
          property: connectionString
      - key: SECRET_KEY
        value: your-secure-secret-key
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "e-mrkt-api.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: CLOUD_NAME
        value: "olaneat"
      - key: CLOUD_API_KEY
        value: "995826528841416"
      - key: CLOUD_SECRET_KEY
        value: "NbfvCGcLJDWjD9w5cNU3jsIK6vs"
      - key: CLOUDINARY_URL
        value: "cloudinary://995826528841416:NbfvCGcLJDWjD9w5cNU3jsIK6vs@olaneat"
      - key: SUPERUSER_USERNAME
        value: neat
      - key: SUPERUSER_EMAIL
        value: admin@abc.com
      - key: SUPERUSER_PASSWORD
        value: password
      - key: SUPERUSER_ROLE
        value: admin