app = "commerce"
primary_region = "fra"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "8000"
SECRET_KEY = django-insecure-g^w5$oj^unmw^p*(&jpb5klc1a7zn-#baxyj(a0+dqd=0+gy2*  # Generate a strong key
DEBUG = "False"
ALLOWED_HOSTS = "commerce"  # Replace with your app name

# Database environment variables (provided by Fly.io after setup)
PGDATABASE = "e_market"
PGUSER = "postgres"
PGPASSWORD = "sfMAa4eAvuDLlZ4"
PGHOST = "commerce.internal"
PGPORT = "5432"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]