# Generated by Django 4.2 on 2023-04-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='dispaly_image',
            field=models.ImageField(blank=True, upload_to='asset/display-img'),
        ),
    ]
