# Generated by Django 4.2 on 2023-07-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='dispaly_image',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='email',
        ),
    ]
