# Generated by Django 4.2 on 2023-07-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_remove_userprofilemodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
