# Generated by Django 4.2 on 2023-06-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productmodel_specifications_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSpecificationModel',
        ),
    ]
