# Generated by Django 4.2 on 2023-05-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_categorymodel_options_categorymodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
