# Generated by Django 4.2 on 2023-05-23 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productmodel_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ('created_on',),
            },
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='products.manufacturermodel'),
        ),
    ]
