# Generated by Django 4.2 on 2023-06-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
