# Generated by Django 4.2 on 2023-05-23 22:12

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productmodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturermodel',
            name='img',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image/manufacturer'),
            preserve_default=False,
        ),
    ]
