# Generated by Django 4.2 on 2023-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productmodel_line_productmodel_size_productmodel_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='ram',
            new_name='bluetooth',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='wlan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
