# Generated by Django 4.2 on 2023-05-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_manufacturermodel_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturermodel',
            options={'ordering': ('-created_on',), 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
