# Generated by Django 4.2 on 2023-06-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productmodel_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='memory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
