# Generated by Django 4.2 on 2025-01-27 22:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmodel_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images/category'),
        ),
    ]
